### ISSUE TITLE
Огненные источники света

### ISSUE THREAD

**Issue by Agoichi** [crystallpunk-14/crystallpunk-docs#14]
# Предлагаемые источники освещения
## Новые
- Настенный факел
- Держатель факела
- Маслянный светильник
## Редизайн текстуры
- Светильник (фонарь)
- Костёр
- Камин
- Факел

# Редизайн освещения

Предлагаю сменить цветовую гамму света костра, камина и прочих чтобы они были одинаковые.
Если честно я считаю что лучший свет у факела и камина потому будет резонно взять их свет за основу для открытых источников огня. 
Я считаю что для открытых источников огня стоит взять более теплую оранжевую гамму камина.
Для ламп, свечей, фонарей же идеально подойдет цветовой выбор костра.

### Затухение\Тушение
Думаю стоит также реализовать затухание для каждого предмета который работает на огне на подобии факеда. Тоесть для камина, костра, лампы и маслянного светильника. 
Также интересным взаимодействием могло бы быть тушение открытых источников освещения водой.

### Удары факелом
Думаю стоило бы дать возможность атаковать факелом. Ведь факел в самом деле грозное оружие.

### Готовка
Сделать костёр аналогом электрогриля. А как иначе без этого в фентези мире

**Comment by TheShuEd** [comment]
Просьба перенести в основной репозиторий, а не геймдизайн
